### ISSUE TITLE
Deploy Blog Application

### ISSUE THREAD

**Issue by juanitozambada** [PacktPublishing/Modern-Full-Stack-React-Projects#85]
I can't Deploy Blog Application  with GitHub Actions.

The error is:
Unable to resolve action actions/ckeckout, repository not found

**Comment by omnidan** [comment]
Hi @juanitozambada! Thanks for reporting the issue.

To be able to reproduce your issue, can you please let me know in which chapter this issue happened, and which steps you did that caused this issue?

Are you using a private repository? If so, you might need to provide your GitHub Personal Access Token (PAT), as follows:

```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
```

Alternatively, please try using a public repository for now to see if that resolves the issue.

Hope this helped you out!
